first_number= input("enter your first number : ")
second_number= input("enter your second number : ")
sum_numbers=int(first_number)+int(second_number)
subtract_numbers=int(first_number)-int(second_number)
multiplication_numbers=int(first_number)*int(second_number)
division_numbers=int(first_number)/int(second_number)
print("the sum is : ",sum_numbers)
print("the subtraction is : ",subtract_numbers)
print("the multiplication is : ",multiplication_numbers)
print("the division is : ",division_numbers)